/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CourseId = IDL.Nat;
export const EnrollmentId = IDL.Nat;
export const Course = IDL.Record({
  'id' : CourseId,
  'title' : IDL.Text,
  'trainerBio' : IDL.Text,
  'fees' : IDL.Nat,
  'trainerName' : IDL.Text,
  'shortDescription' : IDL.Text,
  'batchTimings' : IDL.Text,
  'zoomLink' : IDL.Text,
  'fullDescription' : IDL.Text,
  'syllabus' : IDL.Vec(IDL.Text),
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const Enrollment = IDL.Record({
  'id' : EnrollmentId,
  'paymentStatus' : PaymentStatus,
  'studentName' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'phoneNumber' : IDL.Text,
  'courseId' : CourseId,
});

export const idlService = IDL.Service({
  'createCourse' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
      ],
      [CourseId],
      [],
    ),
  'createEnrollment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, CourseId],
      [EnrollmentId],
      [],
    ),
  'deleteCourse' : IDL.Func([CourseId], [], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
  'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
  'getEnrollment' : IDL.Func([EnrollmentId], [IDL.Opt(Enrollment)], ['query']),
  'getEnrollmentsByCourse' : IDL.Func(
      [CourseId],
      [IDL.Vec(Enrollment)],
      ['query'],
    ),
  'getEnrollmentsByStatus' : IDL.Func(
      [PaymentStatus],
      [IDL.Vec(Enrollment)],
      ['query'],
    ),
  'markEnrollmentPaid' : IDL.Func([EnrollmentId], [], []),
  'updateCourse' : IDL.Func(
      [
        CourseId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CourseId = IDL.Nat;
  const EnrollmentId = IDL.Nat;
  const Course = IDL.Record({
    'id' : CourseId,
    'title' : IDL.Text,
    'trainerBio' : IDL.Text,
    'fees' : IDL.Nat,
    'trainerName' : IDL.Text,
    'shortDescription' : IDL.Text,
    'batchTimings' : IDL.Text,
    'zoomLink' : IDL.Text,
    'fullDescription' : IDL.Text,
    'syllabus' : IDL.Vec(IDL.Text),
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const Enrollment = IDL.Record({
    'id' : EnrollmentId,
    'paymentStatus' : PaymentStatus,
    'studentName' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'phoneNumber' : IDL.Text,
    'courseId' : CourseId,
  });
  
  return IDL.Service({
    'createCourse' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [CourseId],
        [],
      ),
    'createEnrollment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, CourseId],
        [EnrollmentId],
        [],
      ),
    'deleteCourse' : IDL.Func([CourseId], [], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllEnrollments' : IDL.Func([], [IDL.Vec(Enrollment)], ['query']),
    'getCourse' : IDL.Func([CourseId], [IDL.Opt(Course)], ['query']),
    'getEnrollment' : IDL.Func(
        [EnrollmentId],
        [IDL.Opt(Enrollment)],
        ['query'],
      ),
    'getEnrollmentsByCourse' : IDL.Func(
        [CourseId],
        [IDL.Vec(Enrollment)],
        ['query'],
      ),
    'getEnrollmentsByStatus' : IDL.Func(
        [PaymentStatus],
        [IDL.Vec(Enrollment)],
        ['query'],
      ),
    'markEnrollmentPaid' : IDL.Func([EnrollmentId], [], []),
    'updateCourse' : IDL.Func(
        [
          CourseId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };