/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : CourseId,
  'title' : string,
  'trainerBio' : string,
  'fees' : bigint,
  'trainerName' : string,
  'shortDescription' : string,
  'batchTimings' : string,
  'zoomLink' : string,
  'fullDescription' : string,
  'syllabus' : Array<string>,
}
export type CourseId = bigint;
export interface Enrollment {
  'id' : EnrollmentId,
  'paymentStatus' : PaymentStatus,
  'studentName' : string,
  'email' : string,
  'timestamp' : bigint,
  'phoneNumber' : string,
  'courseId' : CourseId,
}
export type EnrollmentId = bigint;
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null };
export interface _SERVICE {
  'createCourse' : ActorMethod<
    [
      string,
      string,
      string,
      Array<string>,
      string,
      string,
      string,
      bigint,
      string,
    ],
    CourseId
  >,
  'createEnrollment' : ActorMethod<
    [string, string, string, CourseId],
    EnrollmentId
  >,
  'deleteCourse' : ActorMethod<[CourseId], undefined>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllEnrollments' : ActorMethod<[], Array<Enrollment>>,
  'getCourse' : ActorMethod<[CourseId], [] | [Course]>,
  'getEnrollment' : ActorMethod<[EnrollmentId], [] | [Enrollment]>,
  'getEnrollmentsByCourse' : ActorMethod<[CourseId], Array<Enrollment>>,
  'getEnrollmentsByStatus' : ActorMethod<[PaymentStatus], Array<Enrollment>>,
  'markEnrollmentPaid' : ActorMethod<[EnrollmentId], undefined>,
  'updateCourse' : ActorMethod<
    [
      CourseId,
      string,
      string,
      string,
      Array<string>,
      string,
      string,
      string,
      bigint,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];